### ISSUE TITLE
@lazuardifath -> Change Admin LTE to vue js

### ISSUE THREAD

**Issue by lazuardifath** [malamma/Laravel-Sense#1]
Tidak bisa integrasi dengan Vue.js dikarenakan @malamma udah set ke adminLTE. just use Admin-LTE until project finished. Thanks

**Comment by malamma** [comment]
yaudah pake adminLTE aja

**Comment by lazuardifath** [comment]
> yaudah pake adminLTE aja

Oke done ya, gua close
